insert into document (code, name) values (1, 'Свидетельство о рождении');
insert into document (code, name) values (2, 'Паспорт гражданина РФ');
insert into document (code, name) values (3, 'Паспорт иностранного гражданина');
insert into document (code, name) values (10, 'Вид на жительство иностранного гражданина');
insert into document (code, name) values (11, 'Разрешение на временное проживание');
insert into document (code, name) values (12, 'Загранпаспорт гражданина РФ');
insert into document (code, name) values (13, 'Удостоверение личности военнослужащего РФ');
insert into document (code, name) values (15, 'Временное удостоверение личности гражданина РФ');
insert into document (code, name) values (18, 'Паспорт гражданина СССР');
insert into document (code, name) values (91, 'Другое');

insert into country values(643, 'Российская Федерация');
insert into country values(554, 'Новая Зеландия');
insert into country values(392, 'Япония');
insert into country values(203, 'Чешская Республика');
insert into country values(112, 'Республика Беларусь');
insert into country values(528, 'Королевство Нидерландов');
insert into country values(804, 'Украина');
insert into country values(126, 'Литовская Республика');
insert into country values(840, 'Соединённые Штаты Америки');
insert into country values(826, 'Соединённое Королевство Великобритании и Северной Ирландии');